### ISSUE TITLE
unresolved scalaz-stream dependency (2.11;0.5a)

### ISSUE THREAD

**Issue by ianweatherhogg** [vngrs/sample-compositional#1]
Hi

# Problem
`sbt compile` gives an unresolved scalaz-stream dependency

```
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: org.scalaz.stream#scalaz-stream_2.11;0.5a: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn] 	Note: Unresolved dependencies path:
[warn] 		org.scalaz.stream:scalaz-stream_2.11:0.5a
[warn] 		  +- org.specs2:specs2_2.11:2.4.14 (/common/Code/scala/github/vngrs/sample-compositional/project/LogicBuild.scala#L24)
[warn] 		  +- com.vngrs:proto-ragnar_2.11:0.1-SNAPSHOT
sbt.ResolveException: unresolved dependency: org.scalaz.stream#scalaz-stream_2.11;0.5a: not found
	at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:278)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:175)
```

# Solution
Adding 

```
resolvers += "Scalaz Bintray Repo" at "http://dl.bintray.com/scalaz/releases"
```

to `buildSettings` in `LogicBuild.scala` solves the issue

# Further

[scalaz-stream](https://github.com/scalaz/scalaz-stream) `README` does suggest using the `Bintray Repo` otherwise (...and I think I'm correct in saying...) `sbt` will check [typesafe](http://repo.typesafe.com/typesafe/releases/org/scalaz/stream/scalaz-stream_2.10/) repository, for which only version 2.10 exists.

Cheers

Ian

**Comment by mehmeteking** [comment]
Verified and solved. Thanks :)
